部署和环境需求
* 拓扑结构：

* 硬件配置建议
云平台采用 DELL 的专业高端服务器R701，配备了 16G 的大容量内存，操作系统使用目前最稳定的 FreeBSD 操作系统，并通过服务器冗余和实时备份来实现了７Ｘ２４小时的不间断服务。数据库采用 Mysql 来搭建集群，通过主从结构和数据分表来提高可支撑的数据量和服务性能；通过定期的全量备份，以及独立服务器的实时备份，来最大程度的保证了数据的安全性。

* 软件配置建议

** 平台的设计性能
1. 可以支撑 1000 万注册用户。
2. 可以支撑 500 万访问量/天。
3. 页面响应时间小于400毫秒。

** 服务器架构
1. 服务器采用开源的 Linux 操作系统，系统有非常好的稳定性，并相对 Windows 可以节省成本。
2. WEB 服务采用 Apache。Apache 是现在在广泛使用的 WEB 服务端软件，非常稳定，并且有很好的性能，相关维护文档也很丰富。
3. 图片服务采用单独的域名，以减少用户浏览器上传 Cookie 带来的流量；图片 WEB 服务器用NGINX+CDN来提高静态文件的访问性能。

** 数据库架构
1. 采用MYSQL数据库５.x版本，使用 innodb 引擎，通过数据库的事务性来保证用户订单以及支付操作的完整性。
2. 读写分离设计，数据库采用一台Master+两台Slave为一组的模式，每个大的功能中心根据负载使用多组数据库服务器。
3. 为提高数据库性能，对于用户表、订单表，采用分表的设计方式，来减少每个表中的数据量。
4. KVDB 的使用。KVDB 是一种简单的“键－值”存储方式，为提高性能，一般存储在内存中，并有自己的持久化机制，相对 MySQL 有更好的读写性能。KVDB 用来存储热点数据，以提高响应速度。

** CDN 静态资源加速方案

CDN的全称是Content Delivery Network，即内容分发网络。其基本思想是尽可能的避开互联网上有可能影响数据传输速度和稳定性的环节，使内容的传输速度更快、更稳定。通过在网络各处放置节点服务器所构成的在现有互联网基础之上的一层智能虚拟网络，CDN系统能够实时的根据网络流量和各节点的连接、负载状况以及到各用户的距离和响应时间等综合信息将用户的请求重新导向离用户最近的服务器节点上。其根本目的是使用户可以就近的获取所需内容，避开Internet网络拥挤的状况，提高用户访问网站的响应速度。从技术上全面解决由于网络带宽小、用户访问量大、网点分布不均等原因所造成的用户访问网站响应速度慢的问题。
网站的图片和样式、ＪＳ等资源采用ＣＤＮ技术，使用户可以更快的从有最佳路由的服务器上获取到相关资源，可以减少用户下载、展示页面所需要的时间，提升用户体验。

** PHP 开发方案

采用 PHP 作为开发语言。PHP 具有以下优点：
1. 跨平台，性能优越；
2. 历史悠久，语法稳定，易于保护投资的连贯性；
3. 支持 WebService、Ajax、XML 等主流技术，足够应用；
4. 开发社区成熟，易于组建开发团队，易于维护；
5. PHP 5 已经有成熟的面向对象体系，能够适应基本的面向对象要求，适合开发大型项目；
6. 淘宝网、Yahoo、163、Sina 等很多大型门户都选用 PHP 来作为他们的开发语言；

开发中采用 SVN 管理源码。源代码进入 SVN 后，历史记录不可更改。这个特性很有利于源代码的安全保护、责任的分配。
