* lvresize
http://serverfault.com/questions/574178/how-can-i-resize-my-logical-volume-in-centos6
lvresize -l +100%FREE /dev/centos/root
xfs_growfs /dev/centos/root
mkfs.xfs /dev/centos/home -f


* Understanding Exit Codes and how to use them in bash scripts
touch /root/test 2> /dev/null
if [ $? -eq 0 ]
then
  echo "Successfully created file"
  exit 0
else
  echo "Could not create file" >&2
  exit 1
fi

$ ./tmp.sh && echo "bam" || (sudo ./tmp.sh && echo "bam" || echo "fail")
Could not create file
Successfully created file
bam

* Batch convert gbk files to utf-8 using iconv

find . -type f -name '*.cue' -exec sh -c "iconv -f GBK -t UTF-8 '{}' > '{}'.utf8" \; -exec mv "{}".utf8 "{}" \;

* execute the following commands to clear history forever

history -c && history -w

* Easy way to get mac address of network card

# VARIABLE="$(cat /sys/class/net/$IFACE/address)"
read -r MACADDRESS < /sys/class/net/$iFACE/address

* [[http://stackoverflow.com/questions/15461737/how-to-execute-xpath-one-liners-from-shell][How to execute XPath one-liners from shell?]]
xmllint --xpath '//mac/@address' /etc/libvirt/qemu/t2.xml
echo 'cat /root/child/@*[starts-with(name(),"attr")]' | xmllint --shell data.xml
xmllint --xpath 'string(//ResponseType)' Det.xml
/*[local-name()='Envelope']/*[local-name()='Body']/*[local-name()='grtHgetRed']/*[local-name()='ResponseType']
test=$(xmllint --xpath "string(//body/value/@name)" test.xml)
'//span[@class="version"]/text()'

* [[http://stackoverflow.com/questions/20913635/how-to-read-multi-line-input-in-a-bash-script][How to read multi-line input in a Bash script?]]
You just have to decide how much to read.

If this is the only input, you could read until end of file. This is how most UNIX utilities work:

#!/bin/bash
echo "Pipe in certificate, or paste and it ctrl-d when done"
keyvariable=$(cat)
If you want to continue reading things later in the script, you can read until you see a blank line:

#!/bin/bash
echo "Paste certificate and end with a blank line:"
keyvariable=$(sed '/^$/q')
If you want it to feel more like magic interactively, you could read until the script has gone two seconds without input:

#!/bin/bash
echo "Paste your certificate:"
IFS= read -d '' -n 1 keyvariable
while IFS= read -d '' -n 1 -t 2 c
do
    keyvariable+=$c
done
echo "Thanks!"

* npm
npm config set registry https://registry.npm.taobao.org

* inbox
How to find unused IP Address on a network?
nmap -sP -PR '192.168.1.*'

* hostname @ centos 7
  hostnamectl set-hostname client.itzgeek.com

echo -e "\n127.0.0.1\n\n3650\n" | ./lc-tlscert
( echo '' ; echo '127.0.0.1' ; echo '';  echo '3650' ) | ./lc-tlscert


docker run --rm --name lscert-www -v "$(pwd)/cert":/usr/share/nginx/html:ro nginx
curl $(docker inspect --format '{{ .NetworkSettings.IPAddress }}' lscert-www)/logstash-forwarder.crt

How do I extract the contents of an rpm?


$ rpm2cpio php-5.1.4-1.esp1.x86_64.rpm | cpio -idmv


docker ps -a | grep Exit | awk '{ print $1 }' | xargs -r docker rm

ssh otherhost /bin/bash << EOF
ls some_folder;
./someaction.sh 'some params'
pwd
./some_other_action 'other params'
EOF


ssh address-of-B 'wget -O - http://server-C/whatever' >> whatever


* ssh-agent 免部署秘钥
ssh-agent代理允许使用ssh登陆已经配置ssh信任关系的机器，并在这些已经配置同样信任关系的机器间跳转，而不需要再次鉴权。

例如： 在不设置ssh-agent的情况下 机器bbb,ccc和ddd上都已经配置了aaa机的公钥
从aaa机器登陆bbb后，如果需要登陆ccc或者ddd机器 就必须是先退出bbb再重新登陆ccc或者ddd
root@aaa$ ssh bbb
root@bbb$ ssh ccc 如果从bbb上登陆ccc， 会因为没有信任关系提示要求输入密码
root@ccc's password:

这就是ssh-agent要解决的问题，通过所有服务器上存放私钥副本，可以不需要暴露私钥。

* patch use xargs
cat patch-chatroom | xargs -I file cp file ../../tag/v2.0/src/file

** 从 1850 版到现在，由 luot 提交的文件，去掉 /trunk/src 前缀， 输出
svn log -r 1850:HEAD -v | awk '/^r[0-9]+ / {user=$3} /trunk\/src/ \
   {if (user=="luot") {print $2}}' | sort | uniq | sed s@/trunk/src/@@ \
   | xargs -i echo {} {}



** ssh tar
ssh user@host "tar -zcf - /path/to/dir" > dir.tar.gz
// Create a local compressed tarball from remote host directory

如何查看某端口号被哪些程序占用？
lsof -i:3000

撤销 git add
git reset HEAD


** osx
sudo scutil --set ComputerName "newname"
sudo scutil --set LocalHostName "newname"
sudo scutil --set HostName "newname"

http://apple.stackexchange.com/questions/107307/how-can-i-install-the-command-line-tools-completely-from-the-command-line

* osx

** hide user
sudo defaults write /Library/Preferences/com.apple.loginwindow HiddenUsersList -array-add user1 user2
sudo defaults delete /Library/Preferences/com.apple.loginwindow HiddenUsersList
sudo chflags hidden /Users/USERNAME

** netstat
lsof -Pni4 | grep LISTEN | grep php

* 网站克隆
wget -r -p -np -k http://www.renrendai.com/
